# Generated by Django 4.0.6 on 2022-07-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
                ('aircraft', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('errors_count', models.IntegerField()),
                ('info_count', models.IntegerField()),
            ],
        ),
    ]
